######################################################################
# Automatically generated by qmake (3.0) Thu Nov 30 13:30:41 2017
######################################################################

TEMPLATE = app
TARGET = g5
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += mainwindow.h ui_mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
